### PR TITLE
Add Fast Charge toggle in Battery Settings

### PR DESCRIPTION
**Pull request by ty85sr**
These commits add a Fast Charge toggle in Battery settings. The toggle enables 120w charging feature for the Xiaomi Mix 4 (odin).

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
Do you compiled this and its working for you?

**Comment by ty85sr** [comment]
Yes, it has worked for me on a build I compiled a few days ago

**Comment by NurKeinNeid** [comment]
Thank you! I will squash your commits, correct authorship and will merge.

**Comment by NurKeinNeid** [comment]
Merged:
https://github.com/DerpFest-AOSP/packages_apps_Settings/commit/d1642682baeed0018544280af18b5f4b355da7ed

**Pull request closed without merging**
