### PR TITLE
Settings: Introduce pocket judge [2/2] 

### PR DESCRIPTION
**Pull request by youngherna**

### CODE REVIEW

**Comment by youngherna** [comment]
Both commits can be run in 1

**Comment by youngherna** [comment]
Both commits can be run in 1

**Comment by NurKeinNeid** [comment]
What happened that you closed it again? Is there anything I can do to help?

**Comment by youngherna** [comment]
Im testing it I was thinking of integrating this.

**Comment by youngherna** [comment]
> What happened that you closed it again? Is there anything I can do to help?

Im testing it.I wanted to integrate it.

**Pull request closed without merging**
