### PR TITLE
Settings: Update zh-rCN translation

### PR DESCRIPTION
**Pull request by ianchb**

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
I imported lineage translations and removed all duplicates from your previous translation and you recognized it and extended it properly now. Very good job! Thank you!

**Comment by NurKeinNeid** [comment]
Sorry I don't have time for a while to merge new translations

**Comment by ianchb** [comment]
> Sorry I don't have time for a while to merge new translations

OK. I've synced the repo and made this PR a draft currently.
EDIT: I've updated some words from LineageOS.

**Comment by AkaneTan** [comment]
Already merged. Therefore closing this pr.

**Pull request closed without merging**
